export function Footer() {
  return (
    <footer className="bg-foreground text-background py-12">
      <div className="mx-auto max-w-6xl px-6 md:px-8">
        <div className="flex flex-col md:flex-row justify-between items-start md:items-center gap-6">
          <div>
            <p className="font-semibold text-sm tracking-tight mb-1">
              2026 Global CISO Leadership Report
            </p>
            <p className="text-xs text-background/60">
              Executive analysis of 625+ security leaders across North America and international markets
            </p>
          </div>
          <p className="text-xs text-background/40">
            Generated by Superagent.
          </p>
        </div>
        <div className="mt-8 pt-6 border-t border-background/10">
          <p className="text-xs text-background/40">
            Data collected Q4 2025 – Q1 2026. All compensation figures in USD.
          </p>
        </div>
      </div>
    </footer>
  );
}
